### ISSUE TITLE
how to make it work on my desktop could you help me?

### ISSUE THREAD

**Issue by codingvalley** [Saarg/OnTheRoad#10]
it is not showing anything when i try to run it in unity

**Comment by Saarg** [comment]
You'll need to give me more details. What version of Unity are you using? What scene are you trying to run? Do you have errors?

I would suggest getting to know Unity before looking at other projects.

**Comment by codingvalley** [comment]
well i am using the latest version of unity on windows
![screenshot 26](https://user-images.githubusercontent.com/40439082/46598178-d0e66a00-cb00-11e8-8849-5da260151ed4.png)
and it is showing these errors

**Comment by Saarg** [comment]
It looks like you are on Unity 2017.4.12f1 which is definitely not the latest one. Last time I updated the project it was for 2018.1.2f1 as you can see in [ProjectSettings/ProjectVersion.txt](https://github.com/Saarg/OnTheRoad/blob/develop/ProjectSettings/ProjectVersion.txt).

It also looks like part of the project settings and models are missing, it's probably because I use Git-LFS to store big files like images, models or sounds. Do you have git-lfs installed?
I usually recommend  using Sourcetree on windows for unity projects but you should be able to clone this project with any GUI as long as you have git-lfs.

**Comment by codingvalley** [comment]
can you send me the .exe file I want to see how the game works ?

**Comment by Saarg** [comment]
You can find it in the [release tab](https://github.com/Saarg/OnTheRoad/releases) or on [itch.io](https://saarg.itch.io/ontheroad).
